name: Build

on:
  push:
    branches:
      - "stable"
  pull_request:
    branches:
      - "stable"

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install latest Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - run: npm install
      - run: npm run build