name: Test

on:
  push:
  pull_request:

jobs:
  eslint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Build packages
        uses: ./.github/workflows/build.yml

      - name: Lint packages
        run: npm run lint

  jest:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - name: Build packages
        uses: ./.github/workflows/build.yml

      - name: Test packages
        run: npm run test